# Generated by Django 4.0 on 2021-12-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__last_name']},
        ),
    ]
