# Generated by Django 4.0 on 2021-12-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cart_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='temp_id',
        ),
    ]
