# Generated by Django 4.0 on 2021-12-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_promotion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Adress',
        ),
    ]
