# Generated by Django 4.0 on 2021-12-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_likeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedItem',
        ),
    ]
